/* tslint:disable */
/* eslint-disable */
/**
 * Bookify API
 * API del back-end di Bookify
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const AccommodationType = {
    Hotel: 'Hotel',
    Apartment: 'Apartment',
    Resort: 'Resort',
    Villa: 'Villa',
    Hostel: 'Hostel'
} as const;

export type AccommodationType = typeof AccommodationType[keyof typeof AccommodationType];



