/* tslint:disable */
/* eslint-disable */
/**
 * Bookify API
 * API del back-end di Bookify
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AccommodationType } from './accommodation-type';
// May contain unused imports in some cases
// @ts-ignore
import type { Address } from './address';
// May contain unused imports in some cases
// @ts-ignore
import type { Booking } from './booking';
// May contain unused imports in some cases
// @ts-ignore
import type { User } from './user';

/**
 * 
 * @export
 * @interface Accommodation
 */
export interface Accommodation {
    /**
     * 
     * @type {number}
     * @memberof Accommodation
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Accommodation
     */
    'uuid'?: string;
    /**
     * 
     * @type {string}
     * @memberof Accommodation
     */
    'name': string | null;
    /**
     * 
     * @type {AccommodationType}
     * @memberof Accommodation
     */
    'type'?: AccommodationType;
    /**
     * 
     * @type {string}
     * @memberof Accommodation
     */
    'imgUrl': string | null;
    /**
     * 
     * @type {number}
     * @memberof Accommodation
     */
    'ownerId'?: number;
    /**
     * 
     * @type {User}
     * @memberof Accommodation
     */
    'owner'?: User;
    /**
     * 
     * @type {number}
     * @memberof Accommodation
     */
    'addressId'?: number;
    /**
     * 
     * @type {Address}
     * @memberof Accommodation
     */
    'address'?: Address;
    /**
     * 
     * @type {Array<Booking>}
     * @memberof Accommodation
     */
    'bookings'?: Array<Booking> | null;
}



