/* tslint:disable */
/* eslint-disable */
/**
 * Bookify API
 * API del back-end di Bookify
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AddressDto } from './address-dto';

/**
 * 
 * @export
 * @interface AddUserRequestDto
 */
export interface AddUserRequestDto {
    /**
     * 
     * @type {string}
     * @memberof AddUserRequestDto
     */
    'username': string | null;
    /**
     * 
     * @type {string}
     * @memberof AddUserRequestDto
     */
    'firstName': string | null;
    /**
     * 
     * @type {string}
     * @memberof AddUserRequestDto
     */
    'lastName': string | null;
    /**
     * 
     * @type {string}
     * @memberof AddUserRequestDto
     */
    'email': string | null;
    /**
     * 
     * @type {string}
     * @memberof AddUserRequestDto
     */
    'phoneNumber': string | null;
    /**
     * 
     * @type {string}
     * @memberof AddUserRequestDto
     */
    'password': string | null;
    /**
     * 
     * @type {string}
     * @memberof AddUserRequestDto
     */
    'confirmPassword': string | null;
    /**
     * 
     * @type {AddressDto}
     * @memberof AddUserRequestDto
     */
    'address': AddressDto;
}

