/* tslint:disable */
/* eslint-disable */
/**
 * Bookify API
 * API del back-end di Bookify
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Address
 */
export interface Address {
    /**
     * 
     * @type {number}
     * @memberof Address
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'uuid'?: string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'street': string | null;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'number': string | null;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'city': string | null;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'province': string | null;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'postalCode': string | null;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'country': string | null;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'additionalInfo'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Address
     */
    'latitude'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Address
     */
    'longitude'?: number | null;
}

