/* tslint:disable */
/* eslint-disable */
/**
 * Bookify API
 * API del back-end di Bookify
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Accommodation } from './accommodation';
// May contain unused imports in some cases
// @ts-ignore
import type { BookingStatus } from './booking-status';
// May contain unused imports in some cases
// @ts-ignore
import type { User } from './user';

/**
 * 
 * @export
 * @interface Booking
 */
export interface Booking {
    /**
     * 
     * @type {number}
     * @memberof Booking
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Booking
     */
    'uuid'?: string;
    /**
     * 
     * @type {string}
     * @memberof Booking
     */
    'checkInDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof Booking
     */
    'checkOutDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof Booking
     */
    'totalPrice'?: number;
    /**
     * 
     * @type {BookingStatus}
     * @memberof Booking
     */
    'status'?: BookingStatus;
    /**
     * 
     * @type {number}
     * @memberof Booking
     */
    'userId'?: number;
    /**
     * 
     * @type {User}
     * @memberof Booking
     */
    'user'?: User;
    /**
     * 
     * @type {number}
     * @memberof Booking
     */
    'accommodationId'?: number;
    /**
     * 
     * @type {Accommodation}
     * @memberof Booking
     */
    'accommodation'?: Accommodation;
}



