FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /app

COPY . .
RUN dotnet restore "./Bookify.csproj" --disable-parallel

# Install the EF tools
RUN dotnet tool install --global dotnet-ef
ENV PATH="${PATH}:/root/.dotnet/tools"

# Command to run migrations and exit
CMD ["dotnet", "ef", "database", "update"]