version: '3.8'

services:
  nginx-proxy:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - railway-network

networks:
  railway-network:
    driver: bridge