/* tslint:disable */
/* eslint-disable */
/**
 * Bookify API
 * API per testare il back-end di Bookify
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AccommodationType } from './accommodation-type';
// May contain unused imports in some cases
// @ts-ignore
import type { AddressDto } from './address-dto';

/**
 * 
 * @export
 * @interface AccommodationUpdate
 */
export interface AccommodationUpdate {
    /**
     * 
     * @type {string}
     * @memberof AccommodationUpdate
     */
    'name': string | null;
    /**
     * 
     * @type {AccommodationType}
     * @memberof AccommodationUpdate
     */
    'type': AccommodationType;
    /**
     * 
     * @type {number}
     * @memberof AccommodationUpdate
     */
    'ownerId': number;
    /**
     * 
     * @type {AddressDto}
     * @memberof AccommodationUpdate
     */
    'address': AddressDto;
}



