/* tslint:disable */
/* eslint-disable */
/**
 * Token Validation API
 * API per testare la validazione dei token JWT da Keycloak
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AccommodationType } from './accommodation-type';
// May contain unused imports in some cases
// @ts-ignore
import type { AddressDto } from './address-dto';

/**
 * 
 * @export
 * @interface AccommodationRequestDto
 */
export interface AccommodationRequestDto {
    /**
     * 
     * @type {string}
     * @memberof AccommodationRequestDto
     */
    'name': string | null;
    /**
     * 
     * @type {AccommodationType}
     * @memberof AccommodationRequestDto
     */
    'type': AccommodationType;
    /**
     * 
     * @type {AddressDto}
     * @memberof AccommodationRequestDto
     */
    'address': AddressDto;
}



