/* tslint:disable */
/* eslint-disable */
/**
 * Token Validation API
 * API per testare la validazione dei token JWT da Keycloak
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AddressDto
 */
export interface AddressDto {
    /**
     * 
     * @type {string}
     * @memberof AddressDto
     */
    'street': string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressDto
     */
    'number': string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressDto
     */
    'city': string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressDto
     */
    'province': string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressDto
     */
    'postalCode': string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressDto
     */
    'country': string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressDto
     */
    'additionalInfo'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AddressDto
     */
    'latitude'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AddressDto
     */
    'longitude'?: number | null;
}

