/* tslint:disable */
/* eslint-disable */
/**
 * Token Validation API
 * API per testare la validazione dei token JWT da Keycloak
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BookingRequestDto
 */
export interface BookingRequestDto {
    /**
     * 
     * @type {string}
     * @memberof BookingRequestDto
     */
    'checkInDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof BookingRequestDto
     */
    'checkOutDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof BookingRequestDto
     */
    'totalPrice'?: number;
    /**
     * 
     * @type {number}
     * @memberof BookingRequestDto
     */
    'accommodationId'?: number;
}

