/* tslint:disable */
/* eslint-disable */
/**
 * Bookify API
 * API per testare il back-end di Bookify
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Address } from './address';

/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {number}
     * @memberof User
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'uuid': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'username': string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'firstName': string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'lastName': string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'email': string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'phoneNumber': string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'registrationDate'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    'isActive'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    'addressId'?: number;
    /**
     * 
     * @type {Address}
     * @memberof User
     */
    'address'?: Address;
}

